### ISSUE TITLE
Implement new Group Membership UX Design

### ISSUE THREAD

**Issue by erikschlegel** [SimpleCloudManagerProject/SCAMP#128]
Develop the new client interface for the group membership manager wizard, based on new wireframes

Erik

**Comment by erikschlegel** [comment]
This is dependent on the completion of issue #124

**Comment by brentstineman** [comment]
related to #125

**Comment by brentstineman** [comment]
Get current group members -> GET /api/groups/members/
    returns: [ { "name" : "<name>", "id" : "id", "isadmin" : "<true|false>" } ]
**?? return member budget info ??**

Finder user in AD -> GET api/users/ADbyUPN/:upn
    returns: { "name" : "<name>", "upn" : "upn", "tenantID": "<tenantID>" }

Create SCAMP User  -> POST api/users/
    payload: { "name" : "<name>", "upn" : "upn", "tenantID": "<tenantID>", "OrgID" : "<orgId>" }

Add group member -> POST /api/settings/sysadmin/:userid

**Comment by brentstineman** [comment]
See attached for later wireframe images
![group manager - summary](https://cloud.githubusercontent.com/assets/1760519/7983694/903e4e64-0a88-11e5-8bb4-0bbc39b4afa3.png)
![group manager - members](https://cloud.githubusercontent.com/assets/1760519/7983697/923674e4-0a88-11e5-81d1-c11597374fa3.png)

**Comment by vjrantal** [comment]
I started working on this at https://github.com/vjrantal/SCAMP/tree/group-manager and assigned it to myself so that others are aware of the work in progress.

**Comment by brentstineman** [comment]
Awesome Ville!

 

When working on this item, please try to identify “jump in” tasks. We’re doing a hackfest with 2 students from Georgia Tech University next week and my hope is to put them on a couple of those types of items. You can find more about “jump in” items at: http://nikcodes.com/2013/05/10/new-contributor-jump-in/

 

If you find good candidates, simply create an issue for them and apply the “jump in” label. 

 

Thanks!
