### ISSUE TITLE
Refactor API controllers

### ISSUE THREAD

**Issue by brentstineman** [SimpleCloudManagerProject/SCAMP#172]
The existing API controllers do have consistency in named routes and the class names that contains them. This creates some confusion about which controller file to look in for a particular API method. We need to review existing methods and approaches and formulate and implement a plan that provides consistency. 

For reference please review: https://raw.githubusercontent.com/SimpleCloudManagerProject/SCAMP/master/ScampApi/wwwroot/App/specs/rest-api.md

that spec has started to follow a pattern of: /entity taking action on/id of specific entity/component of entity/View to return

for example: /group/:groupId/users/:userid/resources/summary
this queries "group" entity identified by "groupid" asking for a summary (the view) of the resources for the user identified by "userId". 

Plan for refactored implementation should be posted on this issue for discussion before implementation takes place.

**Comment by brentstineman** [comment]
we will refactor api's to follow a plural pattern.... 
/api/groups/{groupid}
/api/users/{userid}

For the rest-api methods referenced above, this would result in the following changes:
Use case 1a: /api/users/{userid}/groups/?filter=admin
Use case 1b: /api/users/{userid}/groups
Use case 2: /api/groups/{groupid}/users
Use case 3: /api/groups/{groupid}/users/{userid}/resources
Use case 4a: /api/users/{userid}/usage/summary
Use case 4b: /api/users/{userid}/budget/summary

**Comment by erikschlegel** [comment]
I like it
