### ISSUE TITLE
error in group display (user with no resources)

### ISSUE THREAD

**Issue by brentstineman** [SimpleCloudManagerProject/SCAMP#206]
when navigating the list of users in the "admin" group view, if you select a user that has no resources, the resource list will continue to display the last list of resources that was successfully retrieved. It should display no resources.

**Comment by vergenzt** [comment]
Working on a PR for this one. :+1:

**Comment by vergenzt** [comment]
The only instance in which I was able to reproduce this was due to invalid data (a resource was listed as a member of a group).
