### ISSUE TITLE
Group management REST API issues

### ISSUE THREAD

**Issue by vjrantal** [SimpleCloudManagerProject/SCAMP#227]
1. ~~When posting a new group, the full group object should be returned after created, but currently the returned object is missing properties. An example of a return value currently: `{"id":"d3470adb-f6c6-493c-8993-eacefa3670ea","name":"Test Group","links":null}`~~
  * Fixed by https://github.com/SimpleCloudManagerProject/SCAMP/pull/231
2. ~~When fetching an individual group, in the returned group's users-list, the property for budget should be `unitsBudgeted`~~
  * Fixed by https://github.com/SimpleCloudManagerProject/SCAMP/pull/245
3. ~~In the same use case as in point 2., the property for manager status should be `isManager` (current is `isAdmin`)~~
  * Fixed by https://github.com/SimpleCloudManagerProject/SCAMP/pull/245
4. ~~Trying to delete a created group results into a `404 - Not Found`-error from the server~~
  * Created as a separate issue https://github.com/SimpleCloudManagerProject/SCAMP/issues/248
5. ~~Adding new users doesn't work, because API `/api/users/FindbyUPN/user` return `401 - Unauthorized`-error~~
  * Fixed by https://github.com/SimpleCloudManagerProject/SCAMP/pull/228
6. ~~When trying to add a user to a group, a `404 - Not Found`-error is received~~
  * Fixed by https://github.com/SimpleCloudManagerProject/SCAMP/pull/245
7. ~~When trying to update a user within a group, `400 - Bad Request`-error is received~~
  * Fixed by https://github.com/SimpleCloudManagerProject/SCAMP/pull/245
8. ~~Security checks missing, because also non-admins can currently create new groups~~
  * Created separately as https://github.com/SimpleCloudManagerProject/SCAMP/issues/251
9. ~~When fetching individual group, the budget property should be as per described in this comment https://github.com/SimpleCloudManagerProject/SCAMP/issues/227#issuecomment-112972622~~
  * Implemented by https://github.com/SimpleCloudManagerProject/SCAMP/pull/245

**Comment by vergenzt** [comment]
**Status:**

**1.** Addressed with #231.
**2/3.** Investigating.
**4.** It looks like this is implemented in marckup/SCAMP@0f42b7a6, there's just no PR yet. I'm going to pull that into my fork and finish it and open a PR.
**5.** You've addressed with #228.
**6/7.** There is an API discrepancy between the frontend and backend. The frontend is expecting POST to add a user to a group, and PUT to modify the user within the group. The backend has PUT add a user to a group, and doesn't have modification implemented. I'm going to create a PR to make the backend match the frontend.

**Comment by brentstineman** [comment]
For point 2, the API will return an property named "budget" that is an object that contains the following payload:
```
{
    "OwnerId" : "<value>",
    "unitsBudgeted" : "<value>",
    "DefaultUserAllocation" : "<value>",
    "EndDate" : "<value>"
}
```

**Comment by vjrantal** [comment]
> For point 2, the API will return an property named "budget" that is an object

@brentstineman How should this object be shown in the UI and how should it change the options offered to the user? For example, should it be so that only the owner of the budget can change the value? Or, that all group managers can still change the budget? Should the budget owner be shown in the group manager view summary tab?

**Comment by brentstineman** [comment]
budget.ownerid = Id of user who created the group and thus allocated a portion of their assigned budget (from the system admin) to that group. Only this user should be able to change these values. In the UI, the area to make these changes should only be visible to the owner, not to any group managers.

**Comment by vjrantal** [comment]
All bullets either fixed or moved to separate issues.
