### ISSUE TITLE
Feasibility check to reduce the dependencies in the front-end

### ISSUE THREAD

**Issue by vjrantal** [SimpleCloudManagerProject/SCAMP#229]
Currently, the front-end depends on jQuery, Bootstrap.js and UI Bootstrap. The sizes of the mentioned frameworks are as follows:

```
$ curl --compressed -so /dev/null https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js -w '%{size_download}'
95786
$ curl --compressed -so /dev/null https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js -w '%{size_download}'
11489
$ curl --compressed -so /dev/null https://cdnjs.cloudflare.com/ajax/libs/angular-ui-bootstrap/0.12.1/ui-bootstrap-tpls.min.js -w '%{size_download}'
17621
```

I believe valid alternatives to reduce dependencies would be to either:

1. Use jQuery and Bootstrap.js
2. Use only UI Bootstrap (which doesn't require jQuery)

When looking at the sizes, by far the biggest gain would be getting rid of jQuery.

**Comment by erikschlegel** [comment]
Hi Ville,

Currently the SCAMP front end uses components from Bootstrap version 3, which has a dependency on JQuery. Angular UI Bootstrap is a very small subset of Bootstrap 3. If you remove the dependency on Bootstrap 3 the front end will break. 

What component(s) are you trying to use from Angular UI bootstrap that isn't available in Bootstrap 3?

Thx,

Erik

**Comment by vjrantal** [comment]
We synced offline with @erikschlegel and both felt that the dependencies SCAMP has at the moment are not super-streamlined, but should be good-enough in a "1.0 timeframe".

The issue with adding additional dependencies towards Angular UI Bootstrap is that later on, if we would like to get rid of that dependency, there would be more to refactor. However, getting features done is more important at this point so whatever gets the job done should be preferred.
