### ISSUE TITLE
Group Manager tab breaks when a Group Admin owns no groups

### ISSUE THREAD

**Issue by shekr** [SimpleCloudManagerProject/SCAMP#232]
A related issue to #75 as you also cannot add a new group in this situation.

**Comment by vjrantal** [comment]
I started today working with a fix, but didn't get it ready yet. If one wants to continue, here https://gist.github.com/vjrantal/12f8ffb5598f53b07ece is what I had so far.

If nobody picks this up, I'll finish the fix tomorrow morning Finland time.
