### ISSUE TITLE
Take group owner into account in the group manager view

### ISSUE THREAD

**Issue by vjrantal** [SimpleCloudManagerProject/SCAMP#244]
See wanted behavior from https://github.com/SimpleCloudManagerProject/SCAMP/issues/227#issuecomment-114469569.

**Comment by vjrantal** [comment]
The referenced pull request implements this as per the referenced comment. In practice, the entire summary tab is now shown unless the logged in user is the owner of the group's budget. There is also backend check in place to respond with 403 error if non-owner tries to edit a group.

While implementing this, I was thinking that it might sometimes be useful to see who is the owner of group's budget, which isn't currently visible in the UI. For example, I might be a group manager in a group, but would want to get the group budget up so I'd need to know who the budget owner is to ask them to do it. @brentstineman What do you think?

**Comment by brentstineman** [comment]
Valid issue. Lets display the owner then. I'm also ok putting the user name into the budget details so we don't need a separate fetch to get it from the DB.

**Comment by vjrantal** [comment]
> Lets display the owner then.

Created this as a separate issue https://github.com/SimpleCloudManagerProject/SCAMP/issues/250.

**Comment by vjrantal** [comment]
Merged in via https://github.com/SimpleCloudManagerProject/SCAMP/pull/245.
