### ISSUE TITLE
Display group owner in group manager

### ISSUE THREAD

**Issue by vjrantal** [SimpleCloudManagerProject/SCAMP#250]
See background from https://github.com/SimpleCloudManagerProject/SCAMP/issues/244#issuecomment-114918695.

**Comment by vjrantal** [comment]
@brentstineman This is now implemented to that the group owner's name is stored under the budget object.

Group summary is shown to all, but the input fields are enabled only if the logged in user is the owner of the group's budget. Group owner name can't ever be edited.

There was already a property called `name` which wasn't really used anywhere so I renamed it to `ownerName` to align with the existing property called `ownerId`. I assumed this is what you meant with:

>  I'm also ok putting the user name into the budget details so we don't need a separate fetch to get it from the DB.

**Comment by brentstineman** [comment]
thinking the group manager UI for add/update should only be visible to: system admin, group admin (that owns the group), and group manager (in that group). If we need the group summary (group name, desc, owner name) displayed to the user, we can likely find room for that on the dashboard (pending consideration #252).

**Comment by vjrantal** [comment]
> should only be visible to: system admin, group admin (that owns the group), and group manager (in that group).

May I assume that the top-level group management navigation tab should be visible to all group admins in general and not just ones that already owns groups? This is the case if a system admin assigns someone (let's say, a new user) as group admin. At first, that new user doesn't have any groups owned, but must be able to see the group management view.

To accomplish this, I believe we would need a "global property" similar to to the current `isSystemAdmin`-property to the root of the user documents (in documentdb).

Furthermore, the front-end UI would need to know if a user is a manager is any of the groups and this information is not currently directly available from the REST API. However, this information can be implies by querying all users' groups and iterating through the list of users in each group and checking if logged in user is a manager in any of those. This could be done more efficiently in the backend so perhaps something to think about.

**Comment by brentstineman** [comment]
agreed on all points. I'll track back the *isSystemAdmin* property and implement similar *isGroupAdmin* and *isGroupManager* flags.

**Comment by vjrantal** [comment]
Merged in via https://github.com/SimpleCloudManagerProject/SCAMP/pull/245.
