### ISSUE TITLE
Error displayed first time new user log in  

### ISSUE THREAD

**Issue by FrankNwabueze** [SimpleCloudManagerProject/SCAMP#254]
When a new user logs in for the first time, on the console report there is an error. 

![screen shot 2015-06-25 at 9 17 23 am](https://cloud.githubusercontent.com/assets/12896812/8355156/84ce4d88-1b1b-11e5-94e8-24d943ff70bf.png)

**Comment by brentstineman** [comment]
I'm working this one.

**Comment by brentstineman** [comment]
situation was where user was a member of a group, but there was no volatile store entry for the user's group budget information. Need to verify that new user gets budget entry when being added.
