### ISSUE TITLE
after logging in, nav menu does not display until page is refreshed

### ISSUE THREAD

**Issue by brentstineman** [SimpleCloudManagerProject/SCAMP#55]
Related to PR #57

When logging in, the left hand nav menu and header to not render until the user refreshes the browser window. These resources should appear immediately for any logged in user but remain invisible for any un-authenticated user.

**Comment by brentstineman** [comment]
Elliot, since you're more Angular savy then I am, I figured you'd be able to fix this faster then I could.

**Comment by brentstineman** [comment]
trying to see if this is blocking the merge

**Comment by brentstineman** [comment]
nope, that wasn't it..

**Comment by vjrantal** [comment]
@brentstineman I didn't notice this was open as a separate issue, but I think #179 also fixes this.

**Comment by brentstineman** [comment]
You are correct @vjrantal I'm closing this issue. :)
