### ISSUE TITLE
Create new SCAMP resource groups

### ISSUE THREAD

**Issue by brentstineman** [SimpleCloudManagerProject/SCAMP#75]
The system administrator can create new SCAMP resource groups. Each group will have a single administrator, and usage quota. This quota will be based on a monthly monetary amount.

**Comment by brentstineman** [comment]
This task should include implementation of budget allocation per http://www.simplecloudmgr.org/docs/features/resourceusage

**Comment by shekr** [comment]
The concept now is that the group admin (not system admin) is the one who creates and allocates budgets to new groups.
