### ISSUE TITLE
Move configuration settings out of app.js

### ISSUE THREAD

**Issue by brentstineman** [SimpleCloudManagerProject/SCAMP#8]
Externalize configuration settings out to a file outside of app.js so that we have centralized configuration that doesn't require touching the "code".

**Comment by GabrieleCastellani** [comment]
I think we have done this in V0.0.1

**Comment by cicorias** [comment]
This was done, unless remnants

More specific on where you see.

There's the debugsettings.json for dev, in deploy these are set as environment variables from portal as app settings so the can be different for slots
